In [8]:
import torch
x = torch.arange(4.0)
x.requires_grad_(True)
print(x.grad)

None


In [9]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [11]:
y.backward() # 对y计算反向传播

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [13]:
x.grad # y对x的梯度


tensor([0., 0., 0., 0.])

In [19]:
print(x)
# 清零，否则PyTorch将累计梯度
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([0., 1., 2., 3.], requires_grad=True)


tensor([3., 3., 3., 3.])