In [1]:
import torch
x = torch.arange(4.0)
x.requires_grad_(True)
print(x.grad)

None


In [2]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [3]:
y.backward() # 对y计算反向传播

In [4]:
x.grad # y对x的梯度


tensor([ 0.,  4.,  8., 12.])

In [5]:
print(x)
# 清零，否则PyTorch将累计梯度
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([0., 1., 2., 3.], requires_grad=True)


tensor([1., 1., 1., 1.])